GET_ALL_TRANSACTIONS = """SELECT * FROM TRANSACTION"""
INSERT_TRANSACTION = """INSERT INTO Transaction VALUES(null, %s, %s, %s)"""
DELETE_TRANSACTION_BY_ID = """DELETE FROM Transaction WHERE id = %s"""